### ISSUE TITLE
Haddock documentation missing on Hackage

### ISSUE THREAD

**Issue by cbdumas** [informatikr/hedis#105]
The [link](https://hackage.haskell.org/package/hedis-0.10.1/docs/Database-Redis.html) to Database.Redis on Hackage says there is no documentation for the module

**Comment by k-bx** [comment]
@cbdumas sorry, what do you mean? Was it rebuilding maybe? I see the documentation by your link.

**Comment by cbdumas** [comment]
Yes it seems to have resolved itself now, sorry for the false alarm.
