### ISSUE TITLE
Disconnect/destroy the connection pool

### ISSUE THREAD

**Issue by dvekeman** [informatikr/hedis#109]
Hi

Is there a way to explicitly disconnect the Connection (Pool)?

Neither the Pool (hidden by the newtype constructor `Conn`) nor the disconnect / destroy functions are exposed.

Thanks

**Comment by k-bx** [comment]
Hmm, not sure what you mean here, `Conn` constructor seems to be exposed:

```
λ import Database.Redis
λ conn <- checkedConnect defaultConnectInfo
λ :i conn
conn :: Database.Redis.Connection       -- Defined at <interactive>:2:1
λ runRedis conn $ set "hello" "hello"
Right Ok
λ runRedis conn $ get "hello"
Right (Just "hello")
λ let (Conn pool) = conn
λ :i pool
pool :: Data.Pool.Pool Database.Redis.ProtocolPipelining.Connection
        -- Defined at <interactive>:8:11
λ import Data.Pool
λ destroyAllResources pool
```

**Comment by dvekeman** [comment]
This session works if you run stack from inside the hedis source but not if hedis is a dependency.

Not an expert haskeller but I think it's due to https://github.com/informatikr/hedis/blob/master/src/Database/Redis.hs#L159 which says `Connection`, not `Connection(..)`

```
λ ~ $ stack ghci --package hedis-0.10.2

λ> import Database.Redis
λ> conn <- checkedConnect defaultConnectInfo
λ> :i conn
conn :: Connection 	-- Defined at <interactive>:4:1
λ> runRedis conn $ set "hello" "hello"
Right Ok
λ> runRedis conn $ get "hello"
Right (Just "hello")
λ> let (Conn pool) = conn

<interactive>:8:6: error:
    Not in scope: data constructor ‘Conn’
    Perhaps you meant variable ‘conn’ (line 4)
```

```
$ stack --version
Version 1.7.0, Git revision 0d848deac8e541aa40c5ab5bc784bb9d3ec2928a x86_64 hpack-0.20.0
```

**Comment by k-bx** [comment]
Sorry, my bad! You are completely right.

PR adding some sort of an API destroying the connections is welcome, exposing something like `Database.Redis.Internal` with exposed constructors would be fine in my opinion as well (with a banner saying that it's not a public API).

**Comment by k-bx** [comment]
Closed via https://github.com/informatikr/hedis/pull/110
