### ISSUE TITLE
Preliminary Sentinel Support

### ISSUE THREAD

**Issue by MichaelXavier** [informatikr/hedis#11]
Since redis sentinel has made it into a release, I thought it would be a good idea to look into what it would take to add sentinel support for hedis:

http://redis.io/topics/sentinel-clients

**Comment by qrilka** [comment]
@borsboom do you still have that code? git returns 404 for that link above

**Comment by borsboom** [comment]
@qrilka I changed my Github username; now it's at https://gist.github.com/borsboom/681d37d273d5c4168723

**Comment by qrilka** [comment]
thank you
