### ISSUE TITLE
Streams support 

### ISSUE THREAD

**Issue by alexjg** [informatikr/hedis#111]
I know the documentation states that this library supports Redis 3.2 but I was wondering if there are any plans to support the new streaming commands (`xread` etc.) available in Redis 5?

**Comment by k-bx** [comment]
PRs are very much welcome, shouldn't be hard to add a new command. Codegen is not used at this point, so just manually adding in the code should be ok.

**Comment by k-bx** [comment]
Yes, sounds good to me. If you'll be unsure on the design -- happy to discuss.
