### ISSUE TITLE
Infinity incorrectly handled in sorted sets

### ISSUE THREAD

**Issue by MichaelXavier** [informatikr/hedis#119]
Sorted sets take `Double` for a score. Operations like `zremrangebyscore` allow you to specify `-inf` or `+inf` to do things like trim all elements greater than or less than a specific score. It also happens to support exclusivity with a leading `(`, e.g. `(5`. The more correct/user friendly approach to fixing this would probably be a breaking API change, adding something like `data ZRangeBound = ExclusiveDiscrete Double | InclusiveDiscrete Double | NegInfinity | PosInfinity`. 

However, a potential short term stop gap would be to literally allow users to construct positive and negative infinity with `Double` and serialize them correctly. You can do `let posInfinity = 1 / 0` and `let negInfinity = negate posInfinity`, and today hedis will actually take these and send them to redis, and redis will not throw, but if you `MONITOR` the redis server it sends something like: `"ZREMRANGEBYSCORE" "bogus" "Infinity" "-Infinity"`, so I think it's just `show`ing the value. To correct this, I think you'd want to use [isInfinite](https://hackage.haskell.org/package/base-4.11.1.0/docs/Prelude.html#v:isInfinite) from `Double`'s `RealFloat` instance to determine if the double is infinite (which will be true for both positive and negative infinity) and then use `d > 0` to determine if it is positive or negative infinity to determine if you should render `+inf` or `-inf`. This wouldn't get you exclusivity but it would get you proper handling of infinity, which is a pretty major part of the sorted set API.

**Comment by MichaelXavier** [comment]
@k-bx My second approach would be a non-breaking API change, it is basically just correctly handling infinite `Double` values + documentation, so I'm confused why you'd need a new API for it. The current behavior when given infinity seems to either be undefined or incorrect.

**Comment by k-bx** [comment]
@MichaelXavier what I propose is to use your non-breaking second approach for current API, while adding your breaking first approach under a new name and mentioning both in each other's docs. Sorry for not making it clear.

**Comment by k-bx** [comment]
Fixed in https://github.com/informatikr/hedis/pull/140
