### ISSUE TITLE
Set command does not support all options

### ISSUE THREAD

**Issue by c00w** [informatikr/hedis#12]
As of 2.6.12 there are a lot more options for SET.

http://redis.io/commands/set

I'm not sure how the best way to do this would be. I'm just going to hardcode a method in my project that does what I want.

**Comment by qrilka** [comment]
#52 fixes this

**Comment by stevladimir** [comment]
Are there updates to this in plans? There is a set of options which are still unsupported

**Comment by k-bx** [comment]
@stevladimir PRs are very much welcome on this one, happy to answer any questions

**Comment by qnikst** [comment]
Hello, we added a support for all `set` options  in a57b9e35. I hope it would work for you.

Currently the options are not totally safe as it's possible to construct values that would not be accepted by Redis. It's likely that we can change the interface before the release as it have to be breaking anyway.

Feel free to reopen ticket in case if it does not.
