### ISSUE TITLE
Build failure with GHC 7.8 and GHC 7.6

### ISSUE THREAD

**Issue by hvr** [informatikr/hedis#135]
Despite announcing compatibility with `base >= 4.6 && < 5`, many releases of `hedis` were suffering from build-failures, see

https://matrix.hackage.haskell.org/package/hedis@1555421027

due to a syntax error in the code at https://github.com/informatikr/hedis/blob/master/src/Database/Redis/PubSub.hs#L25,

```
src/Database/Redis/PubSub.hs:25:28: parse error on input ‘<>’
```

There's no immediate action needed on your part as I've already fixed up the metadata of the affected releases on Hackage to prevent the cabal solver from selecting broken buildplans (see list below), but please take this into account in future releases of `hedis` to prevent the build-report from regressing again.

The revisions I made related to this issues were

 - https://hackage.haskell.org/package/hedis-0.10.1/revisions/
 - https://hackage.haskell.org/package/hedis-0.10.2/revisions/
 - https://hackage.haskell.org/package/hedis-0.10.3/revisions/
 - https://hackage.haskell.org/package/hedis-0.10.4/revisions/
 - https://hackage.haskell.org/package/hedis-0.10.6/revisions/
 - https://hackage.haskell.org/package/hedis-0.10.8/revisions/
 - https://hackage.haskell.org/package/hedis-0.10.9/revisions/
 - https://hackage.haskell.org/package/hedis-0.10.10/revisions/
 - https://hackage.haskell.org/package/hedis-0.11.0/revisions/
 - https://hackage.haskell.org/package/hedis-0.11.1/revisions/
 - https://hackage.haskell.org/package/hedis-0.12.0/revisions/
 - https://hackage.haskell.org/package/hedis-0.12.1/revisions/
 - https://hackage.haskell.org/package/hedis-0.12.2/revisions/

(I made additional revisions to older releases of `hedis` while at it to deal with the missing upper bounds on `network` which also were causing build failures; in total I had to make metadta revisions to 45 `hedis` releases in order to address the visible failures)

and the most recent build report can be inspected at https://matrix.hackage.haskell.org/#/package/hedis

**Comment by k-bx** [comment]
Thanks! Released 0.12.3 with new upper bound.

**Comment by k-bx** [comment]
Oh, also releasing 0.12.4 with network upper bound

**Comment by hvr** [comment]
@k-bx I probably should have been a bit clearer when I wrote

> There's no immediate action needed on your part as I've already fixed up the metadata of the affected releases on Hackage

Please be aware that performing full releases which could instead be represented as metadata updates  are strongly discouraged as they bear a significant negative impact for the Hackage ecosystem (both technical resources as well as human costs - for  the maintainers, for us Hackage trustees as well as users of your library); Hackage metadata revisions elegantly solve all these issues; please help us provide a good user experience for Hackage users by making use of Hackage metadata revisions.

See also https://github.com/haskell-infra/hackage-trustees/blob/master/revisions-information.md for more information about Hackage metadata revisions. If you have any questions please feel free to ask me!
