### ISSUE TITLE
Add a MonadFail instance to the Redis Monad

### ISSUE THREAD

**Issue by kk-hainq** [informatikr/hedis#137]
`MonadFailDesugaring` is now enabled by default from GHC 8.6, I think it would be helpful to add a `MonadFail` instance to the Redis Monad. I can open a PR if no one objects this.

https://gitlab.haskell.org/ghc/ghc/wikis/migration/8.6#monadfaildesugaring-by-default

**Comment by k-bx** [comment]
Sounds great! Would you care to make a PR?

**Comment by kk-hainq** [comment]
Sure, I've created a new PR here #138. There's a failing test but I'm not sure if it's related?

**Comment by k-bx** [comment]
Nah, not related. Thanks!
