### ISSUE TITLE
Thank you for this piece of thoughtful documentation!

### ISSUE THREAD

**Issue by saurabhnanda** [informatikr/hedis#151]
Explaining your library's core monad/typeclasses in simple English is such a breath of fresh-air. Thank you for writing this 👍 

![Screen Shot 2020-06-29 at 2 03 10 PM](https://user-images.githubusercontent.com/28369/85991625-5581c600-ba11-11ea-80f8-600b297c62b7.png)

**Comment by k-bx** [comment]
👍
