### ISSUE TITLE
What does the `Bool` result for `hset` signify? 

### ISSUE THREAD

**Issue by kahlil29** [informatikr/hedis#152]
I've used the `hset` function and it makes the call and returns a `False` but the value was written to the Redis Store perfectly without any issues. 
As per the [Redis docs](https://redis.io/commands/hset), this command returns an `Integer`.

**Comment by k-bx** [comment]
@kahlil29 you are correct, it should probably be an Integer, not a Bool. Would you care enough to make a PR? (with tests)
