### ISSUE TITLE
Don't recommend `forkIO`

### ISSUE THREAD

**Issue by NorfairKing** [informatikr/hedis#165]
The docs for `pubSubForever` use `forkIO`:
https://github.com/informatikr/hedis/blob/f3ce898c479be8591f2e22a9f2f461943d8423be/src/Database/Redis/PubSub.hs#L548
but that's probably not what we want to be using.
For example, if the forked thread crashes, the other threads will not notice.
Could we recommend using `withAsync` instead?

See the docs here for more details on both the problem and the solution: http://hackage.haskell.org/package/async-2.2.3/docs/Control-Concurrent-Async.html

cc @vidocco

**Comment by NorfairKing** [comment]
Here's another example just in case:

```
#!/usr/bin/env stack
-- stack --resolver lts-15.15 script{-# LANGUAGE NumericUnderscores #-}import Control.Concurrentmain :: IO ()
main = do
  putStrLn "Starting our 'server'."
  forkIO $ do            
    putStrLn "Serving..."
    threadDelay 1_000_000
    putStrLn "Oh no, about to crash!"
    threadDelay 1_000_000
    putStrLn "Aaaargh"
    undefined
  threadDelay 5_000_000
  putStrLn "Still running, eventhough we crashed"
  threadDelay 5_000_000                 
  putStrLn "Ok that's enough of that, stopping here."
```
Which outputs:
```
$ ./test.hs
Starting our 'server'.
Serving...
Oh no, about to crash!
Aaaargh
test.hs: Prelude.undefined
CallStack (from HasCallStack):
  error, called at libraries/base/GHC/Err.hs:80:14 in base:GHC.Err
  undefined, called at /home/syd/test/test.hs:17:5 in main:Main
Still running, eventhough we crashed
Ok that's enough of that, stopping here.
```

**Comment by k-bx** [comment]
Yes, this sounds great. Would happily accept a PR on this one.
