### ISSUE TITLE
Build failures in v0.12.15 and newer with GHC 7.10.3 due to `StrictData`

### ISSUE THREAD

**Issue by sjakobi** [informatikr/hedis#177]
See https://matrix.hackage.haskell.org/#/package/hedis.

**Comment by sjakobi** [comment]
As a Hackage trustee, I have created some revisions for the affected versions that should repair the build plans. See e.g. https://hackage.haskell.org/package/hedis-0.15.0/revisions/.

**Comment by k-bx** [comment]
Thank you! I guess no release needed then.
