### ISSUE TITLE
Add support for username in connection url

### ISSUE THREAD

**Issue by davey4** [informatikr/hedis#199]
Redis 6 brought full ACL support by accepting a username in addition to the already existing password.  In `parseConnectInfo` the username currently gets ignored.

**Comment by qnikst** [comment]
Hello, I've added a support for `parseConnectInfo` command as well as introduced `authOpts` with `AuthOpts` datatype.
Checked on a simple ACL in the Redis6.

Please check if the fix workes for you.

It will come in the next release but we need to do quite a bit of work before we can release.
