### ISSUE TITLE
Pubsub and connectMaxIdleTime

### ISSUE THREAD

**Issue by vincentbernat** [informatikr/hedis#20]
Hey!

When using hedis for pub/sub, the connection to Redis supporting pubsub can be closed due to connectMaxIdleTime reached if there are other long running connections. In this case, it is not reopened automatically and we don't have any clue on why nothing is hapenning anymore.

Dunno what the best way to handle is. Maybe disable connectMaxIdleTime when a subscription is active for a given connection?

**Comment by ozataman** [comment]
I don't think a connection being used for PubSub counts as idle. Doesn't resource-pool take them out of the idle pool using `withResource`. They would therefore not be closed, but considered "in use". Right?

**Comment by k-bx** [comment]
Closing this due to what @ozataman said.
