### ISSUE TITLE
We need internals of Connection, or an `isClusteredConn` function

### ISSUE THREAD

**Issue by jberryman** [informatikr/hedis#216]
Just trying out HEAD for the 9.6 support, and I don't think the API supports some existing code we have of the form:

```
case redisConn of
      Redis.NonClusteredConnection _ -> ...
      Redis.ClusteredConnection _ _ -> ...
```

**Comment by jberryman** [comment]
sorry, I realized we're using a fork of hedis; I'm not sure this is relevant

**Comment by qnikst** [comment]
@jberryman actually I would more than happy in case if cluster implementation would be ported upstream, I'm not sure that there is any reason to keep two separate forks each with their own flaws. Unfortunately I'll not be able to maintain server part myself as we are using sentinel based approach, but I would appreciate all PR-s from the fork
