### ISSUE TITLE
Possible silently ignored exceptions

### ISSUE THREAD

**Issue by codygman** [informatikr/hedis#34]
https://github.com/informatikr/hedis/blob/eeb68e1eae6fbb43762f2b073b87eadaee80c813/src/Database/Redis/ProtocolPipelining.hs#L66

"What if hSetBinaryMode in connect throws an exeption? Will the handle be closed? Probably GC will do close it eventually, but I can't check that, especially in presence of unsafeInterleaveIO.

What if hClose in disconnect thows? Will the connEvalTId thread be killed? Probably not."

Context: https://www.reddit.com/r/haskell/comments/3lxy9n/haskell_vs_scala_for_the_core_product/cvamejg

**Comment by qrilka** [comment]
1st part of this issue is covered by #59 and the last one is no longer valid starting from 6e1dc6dcbf2dbb3a51344b199c642b93405e07d1 as there is no such thread anymore

**Comment by k-bx** [comment]
Should be resolved then.
