### ISSUE TITLE
Enhancement request: TLS-over-TCP support

### ISSUE THREAD

**Issue by tomkludy** [informatikr/hedis#41]
I am using a hosted/managed Redis instance within Azure, and by default, that must be accessed with TLS.  Hedis works fine if I enable non-TLS connections to the Azure redis service, but I cannot do so without compromising my app's security (I need to communicate over the internet to redis).

Unfortunately I am just not knowledgeable enough to make this change to hedis myself.  Please consider this as an enhancement request.  Thank you!

**Comment by k-bx** [comment]
I don't think I understand how can one implement this, since redis doesn't support protocol encryption. As [redis documentation](http://redis.io/topics/security) suggests, you can use the [spiped](http://www.tarsnap.com/spiped.html) software.

**Comment by tomkludy** [comment]
spiped did not work for me; however, your comment led me to [stunnel](https://www.stunnel.org/index.html) and that worked, with the following configuration file:

```
client = yes
[redis]
accept = 6379
connect=[insert azure proxy name].redis.cache.windows.net:6380
```

Then I pointed hedis to localhost:6379, and it worked great.

**Comment by k-bx** [comment]
:+1: perfect, good to know that!
