### ISSUE TITLE
_Scan?

### ISSUE THREAD

**Issue by ciez** [informatikr/hedis#63]
Is any of the scan commands implemented?

Are there any plans to do this?

**Comment by qrilka** [comment]
see #55

**Comment by k-bx** [comment]
@ciez yup, see #55 . It's in testing mode, but you can grab that branch and test it for yourself.

**Comment by ciez** [comment]
Thank you very much! Some coincidence ;)

**Comment by qrilka** [comment]
@ciez actually #22 was filed in December already but I hope that we could get scans in master soon

**Comment by ciez** [comment]
да, было бы здОрово.. но и за ветку с решением спасибо!

**Comment by qrilka** [comment]
Oh, shit...
Thanks for spotting this, fixed

**Comment by ciez** [comment]
вам нужен
 zrangebylex с тестом?

запостить сюда?

**Comment by qrilka** [comment]
Спасиб, а можешь как PR в https://github.com/qrilka/hedis/tree/commands-20160226 нарисовать?
Сейчас с тестированием та ветка чтот подвисла и немного запутаные усилия получаются :-\

**Comment by ciez** [comment]
ребята, у меня со временем завал. Работаю денно и нощно.

в гитхабе новичок. долго буду разбираться и моя услуга окажется медвежьей.
А вам ведь всё равно бороться с merge и т.д.

вот версия с <$> для RangeLex. Тест доволен.





2016-03-27 12:53 GMT+02:00 Kirill Zaborsky <notifications@github.com>:

> Спасиб, а можешь как PR в
> https://github.com/qrilka/hedis/tree/commands-20160226 нарисовать?
> Сейчас с тестированием та ветка чтот подвисла и немного запутаные усилия
> получаются :-\
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/informatikr/hedis/issues/63#issuecomment-202033556>
>

-> ManualCommands.hs

{-# LANGUAGE OverloadedStrings, RecordWildCards, FlexibleContexts, InstanceSigs #-}



data RangeLex a = Incl a | Excl a | Minr | Maxr
instance Functor RangeLex where
    fmap::(a -> b) -> RangeLex a -> RangeLex b
    fmap fn ra =
            case ra of
                Minr -> Minr
                Maxr -> Maxr
                (Incl a) -> Incl $ fn a
                (Excl a) -> Excl $ fn a


rangeLex_::RangeLex ByteString -> ByteString
rangeLex_ rl =
    case rl of
        (Incl bs) -> B.concat ["[", bs]
        (Excl bs) -> B.concat ["(", bs]
        Minr -> "-"
        Maxr -> "+"


zrangebylex::(RedisCtx m f) =>
    ByteString  --  key
    -> RangeLex ByteString  --  min
    -> RangeLex ByteString --  max
    -> Maybe(Integer,Integer)  --  (offset,count)
    -> m (f [ByteString])
zrangebylex key min max Nothing =
    sendRequest ["ZRANGEBYLEX", encode key, er min, er max]
    where er = encode . rangeLex_
zrangebylex key min max (Just (offset,count)) =
    sendRequest ["ZRANGEBYLEX", encode key, er min, er max, "LIMIT", encode offset, encode count]
    where er = encode . rangeLex_

**Comment by qrilka** [comment]
Ок, нарисую PR из этого сюда

**Comment by ciez** [comment]
Спасибо..

**Comment by qrilka** [comment]
см. #66

**Comment by k-bx** [comment]
@ciez @qrilka guys, please write in English here, if you'd like to chat in Russian – feel free to do that anywhere else, gitter might be a good service where both of you "have accounts" already. Thanks for your understanding.

**Comment by ciez** [comment]
@k-bx np. 

just curious: is there a Git rule written somewhere that comments must be in English?

with google translate, pretty much any language can be translated.

**Comment by k-bx** [comment]
The rule is not written anywhere, and I think asking readers to use Google Translate is not a good way to go, let's better use Google Translate to post in English. Thank you for your understanding once again.

**Comment by ciez** [comment]
I understand this view. This is not a problem. 

Here is another view:
Understanding between, and convenience for contributors is as important as convenience for potential readers.

I am pretty certain that many more messages are read by intended recipients than by casual visitors. Some messages are intended mainly for the recipient. Even though there is no obvious way to contact them in private.

For some reasons email addresses are hidden. It seems odd that I need to search for some other ways to contact another contributor if I find it more convenient to write in the same language.
