### ISSUE TITLE
Web browsable documentation for Database.Redis module not on hackage

### ISSUE THREAD

**Issue by margaretdax** [informatikr/hedis#71]
Wanted to check out the public API for Database.Redis in browser, noticed I couldn't click the module to get that information in browser. I find this to be a pretty nice experience when evaluating a library / reference docs rather than scanning through a source file.

Please forgive any off terminology, still fairly new to the Haskell community / ecosystem.

**Comment by qrilka** [comment]
That seems to be some problem with building haddocks on hackage time to time, one easy option is to check out previous, as you could see from the [changelog](https://github.com/informatikr/hedis/blob/master/CHANGELOG) there were no particular API changes from 0.7.10 to 0.8.0
@k-bx probaby [neil](http://neilmitchell.blogspot.ru/2014/10/fixing-haddock-docs-on-hackage.html) should be used to upload new library versions?

**Comment by k-bx** [comment]
Yeah. Alternatively, use stackage to view docs http://haddock.stackage.org/nightly-2016-04-20/hedis-0.6.10/Database-Redis.html Unfortunately, it's constrained to an older version https://github.com/fpco/stackage/issues/1247 currently, but hopefully that'll get resolved at some point.

**Comment by qrilka** [comment]
@k-bx my original thought was also to try stackage :)

**Comment by qnikst** [comment]
Now all documentation is available on hackage. I hop that in the future release we will immediately upload haddocks, if thy are not built automatically by hackage.
