### ISSUE TITLE
`liftRedis` of `MonadRedis` is exported but not `returnDecode` of `RedisCtx`

### ISSUE THREAD

**Issue by HanStolpo** [informatikr/hedis#83]
Is there a reason that `liftRedis` is exported but `returnDecode` is not. I ask because the export of `liftRedis` makes it look like it should be possible to create your own `MonadRedis` instance but you can't actually create a useful one since there is no way to create a `RedisCtx` instance.

Basically what I wanted to do is something like this in my code

```haskell
instance (MonadIO m) => MonadRedis (ReaderT App m) where
  liftRedis m = do
    c <- connRedis <$> ask
    (liftIO . runRedis c) m

instance (MonadIO m) => RedisCtx (ReaderT App m) (Either Reply) where
  returnDecode = pure . decode
```

So the instance for `RedisCtx` does not compile because `returnDecode` is not exported.

This is really just a nice to have, but I would say that either `liftRedis` should not be exported or `returnDecode` should also be exported for consistency sake at least.

**Comment by k-bx** [comment]
@HanStolpo @isovector released under 0.9.7!
