### ISSUE TITLE
Clarify Supported Versions of Redis

### ISSUE THREAD

**Issue by andrewthad** [informatikr/hedis#84]
On the package description page for `hedis`, the following statement is present:

> Complete Redis 2.6 command set

This leads me to believe that I should use redis 2.6 or higher (with the understanding that commands added after version 2.6 may not work). From the [travis file](https://github.com/informatikr/hedis/blob/909dffeeaa1ebc48bab55913526f256995afe8cd/.travis.yml#L16), I can see that this library is being tested against 3.0.7. On redis's homepage, the notes for 3.2 currently read:

> Redis 3.2 contains significant changes to the API and implementation of Redis.

As someone new to redis, I have a hard time deciding which version to use based on the available documentation. It would be nice to see a something on the package description that says something along the lines of: "hedis is supported for redis versions ...". For me, that would help speed up the process of getting started with the library.

**Comment by k-bx** [comment]
@andrewthad good point! Latest stable version from redis website is the recommended one, and hedis's goal is to be focused on providing the best support for that version.

Would you care enough to make a PR improving the docs?

**Comment by andrewthad** [comment]
I'd be happy to. I'll get that up soon.

**Comment by andrewthad** [comment]
It's up

**Comment by k-bx** [comment]
Great, up as 0.9.5
