### ISSUE TITLE
Connection to Unix sockets is broken

### ISSUE THREAD

**Issue by alcidesv** [informatikr/hedis#92]
The line below triggers a fail when trying to connect to a local Unix socket:

https://github.com/informatikr/hedis/blob/8fef10139ebca3d4fc83af32a35bc3275aafb38f/src/Database/Redis/ProtocolPipelining.hs#L77

The code was introduced in commit eba98e1eee8923b2f553df181903e8aef05cdf88 by @erickg .

**Comment by k-bx** [comment]
@alcidesv thank you! Released under 0.9.10
