### ISSUE TITLE
connect ignores AUTH and SELECT results

### ISSUE THREAD

**Issue by devwout** [informatikr/hedis#99]
* When a connection password is set in `connectAuth`, but the Redis instance does not require a password, the connection is created anyway.
* When a database number is set in `connectDatabase` but the Redis instance does not have a database with that number, the connection is created anyway.

Both of these effects are probably by design. However, I believe they may be dangerous.

* When a Redis instance is (wrongfully) configured not to require a password, you want to know about this, as this may be a security risk. This one is debatable, as `redis-cli` also continues when a password is set with `-a` but the server does not require one.
* When the number of databases on a Redis instance is lowered and some component is still configured to use a database that does not exist anymore, it will start using database `0` without notice. This may cause it to overwrite data it should not touch.

What do you think? I don't mind writing a PR for this as long as it is desired.

**Comment by k-bx** [comment]
@devwout I think it's a good idea, PR would be appreciated!
